# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_window', '0004_auto_20190424_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='riding',
            field=models.IntegerField(null=True),
        ),
    ]
