# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-23 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190421_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedinuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loggy', to=settings.AUTH_USER_MODEL),
        ),
    ]
